package gov.ankhmorpork.core.util;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Created by spooc on 12/13/2016.
 */
public class Statistics {
    /**
     * Counts the number of occurrences of each unique element in the given set of elements,
     * and returns the resulting map.
     * @param <E>
     * @param elements
     * @return a Map containing the number of unique occurrences of every element e in
     */
    public static <E> Map<E, Long> getFrequencies(Collection<E> elements) {
        return getFrequencies(elements, w -> w);
    }

    /**
     * Applies the elementValueMappingFunction to each of the given elements and returns a
     * Map with the
     * Counts the number of occurrences of unique values generated by applying the
     * elementValueMappingFunction to each element in elements.
     * @param <E> The type of element that will be counted
     * @param <K> The type that will be compared in order to determine the actual frequencies.
     * @param elements a
     * @param elementValueMappingFunction
     * @return
     */
    public static <E, K> Map<K, Long> getFrequencies(
        Collection<E> elements, Function<E, K> elementValueMappingFunction) {
        return elements.stream()
            .collect(Collectors
                .groupingBy(elementValueMappingFunction, Collectors.counting()));
    }
}
